# Generated by Django 4.2 on 2024-08-27 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='product.png', upload_to='images/prodcuts')),
                ('image2', models.ImageField(blank=True, upload_to='images/prodcuts')),
                ('image3', models.ImageField(blank=True, upload_to='images/prodcuts')),
                ('image4', models.ImageField(blank=True, upload_to='images/prodcuts')),
                ('image5', models.ImageField(blank=True, upload_to='images/prodcuts')),
                ('hit', models.PositiveIntegerField(default=0)),
                ('hashtags', models.ManyToManyField(blank=True, to='products.hashtag')),
                ('mark_user', models.ManyToManyField(related_name='mark_product', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
