# Generated by Django 4.2 on 2024-08-22 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='like_users',
        ),
        migrations.AddField(
            model_name='product',
            name='mark_user',
            field=models.ManyToManyField(related_name='mark_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
