# Generated by Django 4.2 on 2024-08-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_like_users_product_mark_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
