# Generated by Django 4.2 on 2024-08-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image2_product_image3_product_image4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product.png', upload_to='images/prodcuts'),
        ),
    ]
